### ISSUE TITLE
Difficulty Verifying Email Source 

### ISSUE THREAD

**Issue by yunissobr** [yusufobr/mern-estate#1]
Email not being verified wether they coming from Google or random source.

https://github.com/yusufobr/mern-estate/blob/5abd6a9964f1d4256408533531b074acb51350cb/api/models/user.model.js#L3-L29

Sol: Add field to your model, google_id and take the token from google to sign in users.

**Comment by yusufobr** [comment]
Hello @yunissobr,

Thank you for recommending the feature. I fixed the issue in the commit below. Please check it and let me know your thoughts:

[commit](https://github.com/yusufobr/mern-estate/commit/0533ea9e3948bb23a2b47a76396fe67423f28dcb)

**Comment by yunissobr** [comment]
great!

**Comment by yusufobr** [comment]
thank you
